### ISSUE TITLE
UNMET PEER DEPENDENCY yo@>=1.0.0

### ISSUE THREAD

**Issue by kikeonline** [yeoman/generator-gruntfile#27]
UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN EPEERINVALID generator-gruntfile@0.1.3 requires a peer of yo@>=1.0.0 but none was installed.

**Comment by arthurvr** [comment]
Just make sure you have the latest `yo` version. `npm i -g yo`

We should probably just get rid of the peer dependency though.

**Comment by SBoudrias** [comment]
Fixed.
